spring.application.name=Employee_Management_System

# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://shinkansen.proxy.rlwy.net:42775/railway
spring.datasource.username=root
spring.datasource.password=QhNfQgOXfbUAmOhXPrkKsTGPVhnUxCmQ

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Cloudinary Configuration
cloudinary.cloud_name=dw8i12gec
cloudinary.api_key=577356439283895
cloudinary.api_secret=f2LpG8VdXJNB2ZJpcGAB4oDNxOc

server.port=${PORT:8080}


jwt.secretKey=n9v66mcvtRRfoWxdkTAb/n4XSjU5t1q6KRjd8piLxs8
jwt.accessToken.expiration=86400000        
jwt.refreshToken.expiration=604800000      


debug=true

server.servlet.logging.request-details=true